import os
from dotenv import load_dotenv
load_dotenv()

FITBIT_API_CALLER_ARN = os.getenv('FITBIT_API_CALLER_ARN')
FITBIT_API_STORE_DATA_LAMBDA_ARN = os.getenv('FITBIT_API_STORE_DATA_LAMBDA_ARN')
API_KEY_NAME = os.getenv('API_KEY_NAME')
USAGE_PLAN_NAME = os.getenv('USAGE_PLAN_NAME')
FITBIT_API_SECRET_MANAGER_ARN = os.getenv('FITBIT_API_SECRET_MANAGER_ARN')
TWITTER_API_SECRET_MANAGER_ARN = os.getenv('TWITTER_API_SECRET_MANAGER_ARN')
GOOGLE_SPREAD_SHEET_API_SECRET_MANAGER_ARN = os.getenv('GOOGLE_SPREAD_SHEET_API_SECRET_MANAGER_ARN')
LINE_NOTIFIER_SECRET_MANAGER_ARN = os.getenv('LINE_NOTIFIER_SECRET_MANAGER_ARN')